-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 12:11:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Positions` (
  `idPosition` INT NOT NULL AUTO_INCREMENT,
  `positionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPosition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `phoneNumber` VARCHAR(20) NULL,
  `eMail` VARCHAR(45) NOT NULL,
  `workExpierence` INT NOT NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idEmployee`),
  INDEX `is_active_idx` (`isActive` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `idDepartment` INT NOT NULL AUTO_INCREMENT,
  `idDepartmentHeadContract` INT NOT NULL,
  `nameDepartment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartment`),
  INDEX `idHead_idx` (`idDepartmentHeadContract` ASC) VISIBLE,
  CONSTRAINT `idDepartmentHead`
    FOREIGN KEY (`idDepartmentHeadContract`)
    REFERENCES `mydb`.`Contract` (`idEmploymentContract`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `idEmploymentContract` INT NOT NULL AUTO_INCREMENT,
  `idPosition` INT NOT NULL,
  `idEmployee` INT NOT NULL,
  `dateHiring` DATE NOT NULL,
  `dateExpiring` DATE NOT NULL,
  `salary` BIGINT NOT NULL,
  `premium` BIGINT NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT 0,
  `idDepartment` INT NOT NULL,
  `rate` INT NOT NULL,
  PRIMARY KEY (`idEmploymentContract`),
  INDEX `idPosition_idx` (`idPosition` ASC) VISIBLE,
  INDEX `idEmployee_idx` (`idEmployee` ASC) VISIBLE,
  INDEX `idDepartment_idx` (`idDepartment` ASC) VISIBLE,
  INDEX `is_active_idx` (`isActive` ASC) VISIBLE,
  INDEX `date_expiring_idx` (`dateExpiring` ASC) VISIBLE,
  CONSTRAINT `idPosition`
    FOREIGN KEY (`idPosition`)
    REFERENCES `mydb`.`Positions` (`idPosition`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `idEmployee`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `mydb`.`Employee` (`idEmployee`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `idDepartment`
    FOREIGN KEY (`idDepartment`)
    REFERENCES `mydb`.`Departments` (`idDepartment`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`m2m-Positions-Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`m2m-Positions-Departments` (
  `idPosition` INT NOT NULL,
  `idDepartment` INT NOT NULL,
  INDEX `idPosition_idx` (`idPosition` ASC) VISIBLE,
  INDEX `idDepartment_idx` (`idDepartment` ASC) VISIBLE,
  PRIMARY KEY (`idPosition`, `idDepartment`),
  CONSTRAINT `idPosition`
    FOREIGN KEY (`idPosition`)
    REFERENCES `mydb`.`Positions` (`idPosition`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `idDepartment`
    FOREIGN KEY (`idDepartment`)
    REFERENCES `mydb`.`Departments` (`idDepartment`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `numberOrder` INT NOT NULL,
  `dateOrder` DATE NOT NULL,
  `idContractAuthor` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `idContractAuthor_idx` (`idContractAuthor` ASC) VISIBLE,
  CONSTRAINT `idContractAuthor`
    FOREIGN KEY (`idContractAuthor`)
    REFERENCES `mydb`.`Contract` (`idEmploymentContract`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transfer` (
  `idOrder` INT NOT NULL,
  `idTransfer` INT NOT NULL,
  `reason` VARCHAR(45) NOT NULL,
  INDEX `idOrder_idx` (`idOrder` ASC) VISIBLE,
  PRIMARY KEY (`idOrder`, `idTransfer`),
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assignment` (
  `idOrder` INT NOT NULL,
  `idAssighnment` INT NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `goal` VARCHAR(45) NOT NULL,
  INDEX `idOrder_idx` (`idOrder` ASC) VISIBLE,
  PRIMARY KEY (`idOrder`, `idAssighnment`),
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `idAdress` INT NOT NULL AUTO_INCREMENT,
  `Country` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NULL,
  `Disctrict` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NULL,
  `Building` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdress`),
  INDEX `country_district_idx` (`Country` ASC, `Disctrict` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Training` (
  `idOrder` INT NOT NULL,
  `idTraining` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `topic` VARCHAR(200) NOT NULL,
  `idAddress` INT NOT NULL,
  INDEX `odOrder_idx` (`idOrder` ASC) VISIBLE,
  PRIMARY KEY (`idOrder`, `idTraining`),
  INDEX `idAddress_idx` (`idAddress` ASC) VISIBLE,
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `idAddress`
    FOREIGN KEY (`idAddress`)
    REFERENCES `mydb`.`Address` (`idAdress`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dismissal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dismissal` (
  `idOrder` INT NOT NULL,
  `idDismissal` INT NOT NULL,
  `dateDismissal` DATE NOT NULL,
  `reason` VARCHAR(200) NOT NULL,
  INDEX `idOrder_idx` (`idOrder` ASC) VISIBLE,
  PRIMARY KEY (`idOrder`, `idDismissal`),
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vacation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vacation` (
  `idOrder` INT NOT NULL,
  `idVacation` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  INDEX `idOrder_idx` (`idOrder` ASC) VISIBLE,
  PRIMARY KEY (`idOrder`, `idVacation`),
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passport` (
  `idEmployee` INT NOT NULL,
  `idPassport` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NULL,
  `patronymic` VARCHAR(45) NULL,
  `birthDate` DATE NOT NULL,
  `serialNumber` VARCHAR(45) NOT NULL,
  `identificationNumber` VARCHAR(45) NOT NULL,
  `idAddress` INT NOT NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idEmployee`, `idPassport`),
  INDEX `idAddress_idx` (`idAddress` ASC) VISIBLE,
  INDEX `idEmployee_idx` (`idEmployee` ASC) VISIBLE,
  INDEX `is_active_idx` (`isActive` ASC) VISIBLE,
  CONSTRAINT `idAddress`
    FOREIGN KEY (`idAddress`)
    REFERENCES `mydb`.`Address` (`idAdress`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `idEmployee`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `mydb`.`Employee` (`idEmployee`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dismissal Contract List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dismissal Contract List` (
  `idOrder` INT NOT NULL,
  `idDismissal` INT NOT NULL,
  `idContract` INT NOT NULL,
  `payment` BIGINT NULL,
  PRIMARY KEY (`idOrder`, `idDismissal`, `idContract`),
  INDEX `idContract_idx` (`idContract` ASC) VISIBLE,
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder` , `idDismissal`)
    REFERENCES `mydb`.`Dismissal` (`idOrder` , `idDismissal`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `idContract`
    FOREIGN KEY (`idContract`)
    REFERENCES `mydb`.`Contract` (`idEmploymentContract`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vacation Contract List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vacation Contract List` (
  `idOrder` INT NOT NULL,
  `idVacation` INT NOT NULL,
  `idContract` INT NOT NULL,
  `payment` BIGINT NULL,
  PRIMARY KEY (`idOrder`, `idVacation`, `idContract`),
  INDEX `idContract_idx` (`idContract` ASC) VISIBLE,
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder` , `idVacation`)
    REFERENCES `mydb`.`Vacation` (`idOrder` , `idVacation`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idContract`
    FOREIGN KEY (`idContract`)
    REFERENCES `mydb`.`Contract` (`idEmploymentContract`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Training Contract List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Training Contract List` (
  `idOrder` INT NOT NULL,
  `idTraining` INT NOT NULL,
  `idContract` INT NOT NULL,
  PRIMARY KEY (`idOrder`, `idTraining`, `idContract`),
  INDEX `idContract_idx` (`idContract` ASC) VISIBLE,
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder` , `idTraining`)
    REFERENCES `mydb`.`Training` (`idOrder` , `idTraining`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `idContract`
    FOREIGN KEY (`idContract`)
    REFERENCES `mydb`.`Contract` (`idEmploymentContract`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assignment Contract List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assignment Contract List` (
  `idOrder` INT NOT NULL,
  `idAssignment` INT NOT NULL,
  `idContract` INT NOT NULL,
  PRIMARY KEY (`idOrder`, `idAssignment`, `idContract`),
  INDEX `idContract_idx` (`idContract` ASC) VISIBLE,
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder` , `idAssignment`)
    REFERENCES `mydb`.`Assignment` (`idOrder` , `idAssighnment`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `idContract`
    FOREIGN KEY (`idContract`)
    REFERENCES `mydb`.`Contract` (`idEmploymentContract`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transfer Contract List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transfer Contract List` (
  `idOrder` INT NOT NULL,
  `idTransfer` INT NOT NULL,
  `idPrevContract` INT NOT NULL,
  `idNewContract` INT NOT NULL,
  PRIMARY KEY (`idOrder`, `idTransfer`, `idPrevContract`),
  INDEX `idContract_idx` (`idPrevContract` ASC, `idNewContract` ASC) VISIBLE,
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder` , `idTransfer`)
    REFERENCES `mydb`.`Transfer` (`idOrder` , `idTransfer`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `idContract`
    FOREIGN KEY (`idPrevContract` , `idNewContract`)
    REFERENCES `mydb`.`Contract` (`idEmploymentContract` , `idEmploymentContract`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- function getShortenedFullName
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE FUNCTION `getShortenedFullName` (id INT) RETURNS VARCHAR(255)
BEGIN
	DECLARE full_name VARCHAR(255);
	SELECT CONCAT(surname, ' ', LEFT(firstName, 1), '. ', LEFT(patronymic, 1), '.') 
		INTO full_name 
        FROM Passport
        WHERE idPassport = id;
    RETURN full_name;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateExpiringContracts
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE `updateExpiringContracts` ()
BEGIN
	UPDATE Contract 
		SET isActive = 1 
        WHERE isActive = 0 AND dateExpiring < CURDATE();
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteUnusedAddresses
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE `deleteUnusedAddresses` ()
BEGIN
	DELETE
		FROM Adress
        WHERE id
			NOT IN (SELECT DISTINCT idAddress FROM Passport UNION SELECT DISTINCT idAddress FROM Training);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
