-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 19:47:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`GuitarManufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GuitarManufacturer` (
  `idGuitarManufacturer` INT NOT NULL,
  `manufacturerInfo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGuitarManufacturer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Guitars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Guitars` (
  `idGuitars` INT NOT NULL,
  `guitarType` VARCHAR(45) NOT NULL,
  `stringCount` VARCHAR(45) NOT NULL,
  `bodyShape` VARCHAR(45) NOT NULL,
  `topDeckMaterial` VARCHAR(45) NOT NULL,
  `bodyMaterial` VARCHAR(45) NOT NULL,
  `colour` VARCHAR(45) NOT NULL,
  `lacquerCoating` TINYINT(1) NOT NULL,
  `idManufacturer` INT NOT NULL,
  `modelName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGuitars`),
  INDEX `idManufacturer_idx` (`idManufacturer` ASC) VISIBLE,
  CONSTRAINT `idManufacturer`
    FOREIGN KEY (`idManufacturer`)
    REFERENCES `mydb`.`GuitarManufacturer` (`idGuitarManufacturer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AccountRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AccountRoles` (
  `idCategory` INT NOT NULL,
  `roleName` VARCHAR(45) NOT NULL,
  `roleTable` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`),
  UNIQUE INDEX `uniqueName` (`roleName` ASC) VISIBLE,
  UNIQUE INDEX `uniqueTable` (`roleTable` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accounts` (
  `idAccount` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `passwordHash` VARCHAR(256) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `idAccountRole` INT NOT NULL,
  PRIMARY KEY (`idAccount`),
  INDEX `idAccountRole_idx` (`idAccountRole` ASC) VISIBLE,
  CONSTRAINT `idAccountRole`
    FOREIGN KEY (`idAccountRole`)
    REFERENCES `mydb`.`AccountRoles` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomersAccountInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CustomersAccountInfo` (
  `idAccount` INT NOT NULL,
  `comments` VARCHAR(200) NOT NULL,
  `registrationDate` DATE NOT NULL,
  PRIMARY KEY (`idAccount`),
  CONSTRAINT `idAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`Accounts` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmployeeRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EmployeeRoles` (
  `idRole` INT NOT NULL,
  `roleName` VARCHAR(45) NOT NULL,
  `roleTable` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRole`),
  UNIQUE INDEX `roleName_UNIQUE` (`roleName` ASC) VISIBLE,
  UNIQUE INDEX `roleTable_UNIQUE` (`roleTable` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmployeeAccountInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EmployeeAccountInfo` (
  `idAccount` INT NOT NULL,
  `employeeRole` INT NOT NULL,
  `rate` INT NOT NULL,
  `salary` BIGINT NOT NULL,
  PRIMARY KEY (`idAccount`),
  INDEX `idRole_idx` (`employeeRole` ASC) VISIBLE,
  CONSTRAINT `idAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`Accounts` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRole`
    FOREIGN KEY (`employeeRole`)
    REFERENCES `mydb`.`EmployeeRoles` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CouriersAccountInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CouriersAccountInfo` (
  `idAccount` INT NOT NULL,
  PRIMARY KEY (`idAccount`),
  CONSTRAINT `idAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`EmployeeAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CustomerOrders` (
  `idOrder` INT NOT NULL,
  `idCustomer` INT NOT NULL,
  `isCourier` INT NOT NULL,
  `status` ENUM('not confirmed', 'confirmed', 'paid', 'delivered') NOT NULL,
  `comment` VARCHAR(200) NULL,
  `paymentType` ENUM('upon receipt', 'upon order') NOT NULL,
  `paymentMean` ENUM('card', 'cash') NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `idCustomer_idx` (`idCustomer` ASC) VISIBLE,
  INDEX `idCurier_idx` (`isCourier` ASC) VISIBLE,
  CONSTRAINT `idCustomer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `mydb`.`CustomersAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCurier`
    FOREIGN KEY (`isCourier`)
    REFERENCES `mydb`.`CouriersAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FavouriteGuitars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FavouriteGuitars` (
  `idAccount` INT NOT NULL,
  `idGuitar` INT NOT NULL,
  PRIMARY KEY (`idAccount`, `idGuitar`),
  INDEX `idGuitar_idx` (`idGuitar` ASC) VISIBLE,
  CONSTRAINT `idAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`CustomersAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGuitar`
    FOREIGN KEY (`idGuitar`)
    REFERENCES `mydb`.`Guitars` (`idGuitars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerShoppingBasket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CustomerShoppingBasket` (
  `idAccount` INT NOT NULL,
  `idGuitar` INT NOT NULL,
  `guitarCount` INT NOT NULL,
  PRIMARY KEY (`idAccount`, `idGuitar`),
  INDEX `idGuitars_idx` (`idGuitar` ASC) VISIBLE,
  CONSTRAINT `idAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`CustomersAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGuitars`
    FOREIGN KEY (`idGuitar`)
    REFERENCES `mydb`.`Guitars` (`idGuitars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GuitarProviders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GuitarProviders` (
  `idProvider` INT NOT NULL,
  `organizationName` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(200) NULL,
  PRIMARY KEY (`idProvider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProvidedGuitars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProvidedGuitars` (
  `idGuitar` INT NOT NULL,
  `idProvider` INT NOT NULL,
  `guitarCount` INT NOT NULL,
  `guitarPrice` BIGINT NOT NULL,
  PRIMARY KEY (`idGuitar`, `idProvider`),
  INDEX `idProvider_idx` (`idProvider` ASC) VISIBLE,
  CONSTRAINT `idProvider`
    FOREIGN KEY (`idProvider`)
    REFERENCES `mydb`.`GuitarProviders` (`idProvider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGuitar`
    FOREIGN KEY (`idGuitar`)
    REFERENCES `mydb`.`Guitars` (`idGuitars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AdministratorsAccountInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AdministratorsAccountInfo` (
  `idAccount` INT NOT NULL,
  PRIMARY KEY (`idAccount`),
  CONSTRAINT `idAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`EmployeeAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DirectorsAccountInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DirectorsAccountInfo` (
  `idAccount` INT NOT NULL,
  PRIMARY KEY (`idAccount`),
  CONSTRAINT `idAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`EmployeeAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProvidersOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProvidersOrders` (
  `idProviderOrder` INT NOT NULL,
  `date` DATE NOT NULL,
  `idProvider` INT NOT NULL,
  `totalPrice` BIGINT NOT NULL,
  `idAdministratorAuthor` INT NOT NULL,
  `idDirectorThatConfirmed` INT NULL,
  `status` ENUM('planning', 'confirmed', 'paid', 'delivered') NOT NULL,
  PRIMARY KEY (`idProviderOrder`),
  INDEX `idProvider_idx` (`idProvider` ASC) VISIBLE,
  INDEX `idAdministrator_idx` (`idAdministratorAuthor` ASC) VISIBLE,
  INDEX `idDirector_idx` (`idDirectorThatConfirmed` ASC) VISIBLE,
  CONSTRAINT `idProvider`
    FOREIGN KEY (`idProvider`)
    REFERENCES `mydb`.`GuitarProviders` (`idProvider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAdministrator`
    FOREIGN KEY (`idAdministratorAuthor`)
    REFERENCES `mydb`.`AdministratorsAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDirector`
    FOREIGN KEY (`idDirectorThatConfirmed`)
    REFERENCES `mydb`.`DirectorsAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProvidersOrdersList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProvidersOrdersList` (
  `idProvidersOrders` INT NOT NULL,
  `idGuitar` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`idProvidersOrders`),
  INDEX `ifGuitar_idx` (`idGuitar` ASC) VISIBLE,
  CONSTRAINT `idGuitar`
    FOREIGN KEY (`idGuitar`)
    REFERENCES `mydb`.`ProvidedGuitars` (`idGuitar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProvidersOrders`
    FOREIGN KEY (`idProvidersOrders`)
    REFERENCES `mydb`.`ProvidersOrders` (`idProviderOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmployeeFines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EmployeeFines` (
  `idFine` INT NOT NULL,
  `idEmployee` INT NOT NULL,
  `fine` BIGINT NOT NULL,
  `reason` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idFine`),
  INDEX `idEmployee_idx` (`idEmployee` ASC) VISIBLE,
  CONSTRAINT `idEmployee`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `mydb`.`EmployeeAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmployeePremiums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EmployeePremiums` (
  `idPremium` INT NOT NULL,
  `idEmployee` INT NOT NULL,
  `premium` BIGINT NOT NULL,
  `reason` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPremium`),
  INDEX `idEmployee_idx` (`idEmployee` ASC) VISIBLE,
  CONSTRAINT `idEmployee`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `mydb`.`EmployeeAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MonthBudget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MonthBudget` (
  `monthBeginning` DATE NOT NULL,
  `income` BIGINT NOT NULL,
  `consumption` BIGINT NOT NULL,
  PRIMARY KEY (`monthBeginning`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passport` (
  `idPassport` INT NOT NULL,
  `idEmployeeAccount` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NULL,
  `patronymic` VARCHAR(45) NULL,
  `birthDate` DATE NOT NULL,
  `serialNumber` VARCHAR(45) NOT NULL,
  `idNumber` VARCHAR(45) NOT NULL,
  `isActive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idPassport`),
  INDEX `idEmployeeAccount_idx` (`idEmployeeAccount` ASC) VISIBLE,
  CONSTRAINT `idEmployeeAccount`
    FOREIGN KEY (`idEmployeeAccount`)
    REFERENCES `mydb`.`EmployeeAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MostPopularGuitars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MostPopularGuitars` (
  `idGuitar` INT NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`idGuitar`),
  CONSTRAINT `idGuitar`
    FOREIGN KEY (`idGuitar`)
    REFERENCES `mydb`.`Guitars` (`idGuitars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MostProfitableGuitars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MostProfitableGuitars` (
  `idGuitar` INT NOT NULL,
  `profit` BIGINT NOT NULL,
  PRIMARY KEY (`idGuitar`),
  CONSTRAINT `idGuitar`
    FOREIGN KEY (`idGuitar`)
    REFERENCES `mydb`.`Guitars` (`idGuitars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reviews` (
  `idReview` INT NOT NULL,
  `idGuitar` INT NOT NULL,
  `idAccount` INT NOT NULL,
  `text` VARCHAR(400) NOT NULL,
  `rating` TINYINT(5) NOT NULL,
  PRIMARY KEY (`idReview`),
  INDEX `idGuitar'_idx` (`idGuitar` ASC) VISIBLE,
  INDEX `idAccount_idx` (`idAccount` ASC) VISIBLE,
  CONSTRAINT `idGuitar'`
    FOREIGN KEY (`idGuitar`)
    REFERENCES `mydb`.`Guitars` (`idGuitars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`Accounts` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Storehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Storehouse` (
  `idGuitar` INT NOT NULL,
  `availableCount` INT NOT NULL,
  `nextSupply` DATE NULL,
  `price` BIGINT NOT NULL,
  PRIMARY KEY (`idGuitar`),
  CONSTRAINT `idGuitar`
    FOREIGN KEY (`idGuitar`)
    REFERENCES `mydb`.`Guitars` (`idGuitars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PurchasedGuitars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PurchasedGuitars` (
  `idAccount` INT NOT NULL,
  `idGuitar` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`idAccount`, `idGuitar`),
  INDEX `idGuitars_idx` (`idGuitar` ASC) VISIBLE,
  CONSTRAINT `idAccount`
    FOREIGN KEY (`idAccount`)
    REFERENCES `mydb`.`CustomersAccountInfo` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGuitars`
    FOREIGN KEY (`idGuitar`)
    REFERENCES `mydb`.`Guitars` (`idGuitars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerOrderList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CustomerOrderList` (
  `idOrder` INT NOT NULL,
  `idGuitar` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `idGuitar_idx` (`idGuitar` ASC) VISIBLE,
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder`)
    REFERENCES `mydb`.`CustomerOrders` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGuitar`
    FOREIGN KEY (`idGuitar`)
    REFERENCES `mydb`.`Guitars` (`idGuitars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
